[package]
name = "relliptic"
version = "0.1.0"
edition = "2021"

[dependencies]
rpolynomial = { git = "https://github.com/varun-doshi/rpolynomial.git", branch = "main"}
modc = { git = "https://github.com/varun-doshi/modc.git", branch = "next"}
primitive-types = "0.12.2"